---
# Template configuration files for app-migration-toolkit

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ app-migration-toolkit_templates_copy }}"
  when: app-migration-toolkit_copy_templates
